### PR TITLE
make config.py py3 compatible

### PR DESCRIPTION
**Pull request by vuLgAr**
info about installing configparser from [here](http://python-future.org/compatible_idioms.html#configparser).

### CODE REVIEW

**Comment by d7415** [comment]
Looks good. I'm not sure about the requirements.txt. I'll have a read up on those.

I'm actually doing the same work (haven't pushed the "messy" stuff yet) on the whole repo. I'll also have to figure out whether it's better to require `configparser` or `future`. `future` probably helps with some other 2/3 problems.

I'm a little tempted to branch it all off and make a py3-only branch to save the hassle...

**Comment by vuLgAr** [comment]
using configparser seems to be the recommended way to go about it according to the latest release section [here](http://python-future.org/whatsnew.html#what-s-new-in-version-0-16-0-2016-10-27).

it references 2 issues [118](https://github.com/PythonCharmers/python-future/issues/118) and [181](https://github.com/PythonCharmers/python-future/issues/181) although im not sure they'd be much applicable to anyone.

the requirements.txt is not complete anyway (just the bot atm) and was only a convenience for myself to install packages with pip so feel free to ignore that.

**Comment by d7415** [comment]
Thanks for doing my work for me :) That makes sense - unsurprisingly Debian's still using 0.15.2, hence my confusion.

I'll look at merging in some form this later tonight.

**Comment by d7415** [comment]
Merged in the `-py3` branches in c58a50cc3e2c6e594539a58a31d83c1c797d247e. I'm not going to put it into master just yet, so I'll leave this open for tracking.

**Pull request closed without merging**
